### ISSUE TITLE
Brakes Network Connection with Netguard/pDNSFilter

### ISSUE THREAD

**Issue by elhennig** [yzyhk904/hifi-maximizer-mod#11]
I use a combination of Netguard and pDNSFilter to secure the network connection on my phone and the mod breaks this setup. Apps cannot access the network anymore after activating the mod.

**Comment by yzyhk904** [comment]
I think SELinux permissive mode is related to this issue. Then this is a feature of this mod for making better audio quality. See README.

You can check this by a command "setenforce 1" to change the mode to usual "Enforcing".
