### ISSUE TITLE
VLC has no audio when using the module

### ISSUE THREAD

**Issue by Cico90** [yzyhk904/hifi-maximizer-mod#12]
Hello,

I have patched the hifi maximizer module on magisk 27, audio is working properly on the device except VLC which doesn't have audio. Both audio and video files there is no audio output on neither speaker nor heaphones. This seems to happen only on VLC , every other app like youtube are working. Hope you can solve this issue.

Device: Samsung Galaxy A5 2017 (Exynos 7880)
OS : lineageOS 19.1 (Android 12.1)
Magisk : 27
Module version : v2.5.4

Peace!

**Comment by yzyhk904** [comment]
Youtube app (not Youtube music app) cannot work with this module except enabling a camera server, so VLS may be the same. Try disabling the camera server described in its README.

If this doesn't help, this may be caused by disabling the effects framework. Uninstall this module.

**Comment by Cico90** [comment]
Is there a way that I can modify the script so it keeps the effects framwork running!?

**Comment by yzyhk904** [comment]
No. Disabling the effects framework is an important main feature of this module.

Edit:
I recommend using only [Audio Jitter Silencer](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer) instead.

**Comment by Cico90** [comment]
I just liked the boost of performance I am getting with this, is there any other module to boost performance the same as this module does without loosing audio!?

**Comment by yzyhk904** [comment]
How about using "extras/jitter-reducer.sh" script in [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer). This can boost performance the same as "Hifi maximizer" on the fly.

**Comment by Cico90** [comment]
I just did! But I got this error after executing --all :

can't create /sys/block/mmcblk0/queue/read_ahead_kb: Permission denied

**Comment by yzyhk904** [comment]
Please read README carefully! Such scripts need "root". 

There are many useful usage samples in "Usage Samples" folder. For example, "jitter-reducer_--boost-max.sh". You can run this on Mixplorer with selection and "Execute" in the 3-dots menu.
