### ISSUE TITLE
Camera/flashlight not functioning

### ISSUE THREAD

**Issue by IamN4m3l3ss** [yzyhk904/hifi-maximizer-mod#13]
Installing this module somehow disables the cameras and disallows the flashlight from turning on as it says the camera is already in use. Opening snapchat or the camera app will produce a error or crash.

Im on note10+ rooted with magisk v27 and running a custom rom on android 14 called project elixir.

![Screenshot_20240325-001028](https://github.com/yzyhk904/hifi-maximizer-mod/assets/76447907/5738a213-9bb2-457e-85bd-b74b7da6112c)
![Screenshot_20240325-001020](https://github.com/yzyhk904/hifi-maximizer-mod/assets/76447907/7b544061-332f-4b21-b849-7f80fcc6cdb9)
![Screenshot_20240325-001001](https://github.com/yzyhk904/hifi-maximizer-mod/assets/76447907/23a74b99-1c2f-4eb2-ba42-325227302a85)

**Comment by yzyhk904** [comment]
It's a main feature, but not a bug at all. Please read README.md.
Because camera servers degrade audio quality, this module disables them!
