### ISSUE TITLE
Change CPU governor from Performance back to Default

### ISSUE THREAD

**Issue by HarriBuh** [yzyhk904/hifi-maximizer-mod#15]
As the title says, I'm pretty sure your mod does change the CPU governor to "performance", for the obvious reason to reduce jitter.
Nevertheless, I want to have my default governor back in action, but I haven't been able to find the change in your code/ script.
Could you lead me towards it, please?

**Comment by yzyhk904** [comment]
I feel you should use [Audio Misc. Settings](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings) for casual music lovers. "Hifi Maximizer" is designed for audiophile experts who prefer audio quality to convenience, security, battery saving, and heating.

If you are an expert more than I think, use "extras/jitter-reducer.sh" in [USB SampleRate Changer](https://github.com/yzyhk904/USB_SampleRate_Changer) which can switch on (boost) and off (revert) each jitter reducing feature on the fly.

**Comment by HarriBuh** [comment]
I didn't ask for your opinion, just for the exact location. I already edited your Hifi Module to my liking and will continue doing so.
I will not hold you responsible for any damages these changes might do to my system, ofc.
I was simply asking for your help, but I'm willing to keep looking without it

**Comment by yzyhk904** [comment]
Why did you ask me that? You have already been editing the module, haven't you?  

If so, you can easily find the place by searching "performance" and "governor".
