### ISSUE TITLE
Youtube doesn't work at all

### ISSUE THREAD

**Issue by Bab1100** [yzyhk904/hifi-maximizer-mod#16]
Hello, I like this module a lot when I used it, it made the music way clearer and better, but the only thing is that YouTube just doesn't work stays on the reloading logo and doesn't do anything.
Flashed this on poco f3 lineageos 20, using kitsune mask with compatibile magisk mirroring module

**Comment by yzyhk904** [comment]
Youtube app changed to need a camera server since some time ago and hasn't been launched since then with this module without an additional setting. Please read "Note1" in README.md.
