### ISSUE TITLE
Device restarts to twrp/reboot

### ISSUE THREAD

**Issue by Bab1100** [yzyhk904/hifi-maximizer-mod#17]
When playing music and pressing the (next) button 5 or more times, the device just restarts to either twrp or does a normal reboot, after deleting the module the problem is fixed, is there a fix for this?
My device is poco f3 using lineagos 20 and using these modules.

> SystemUl Bootloop Saver 

> Systemless Hosts

> Play Integrity Fix

> Magisk Bootloop Protector

> Fullscreen/Immersive Gestures (Q-U)

> Disable Google Analytics

> Compatible Magisk-mirroring

> Thermal QUALCOMM 870 [3.19Ghz]
Medium
v3.0 by Vito Hermawan

> Wifi Bonding 
(Qcom)
1.17 by simonsmh
>Zygisk Lsposed

**Comment by yzyhk904** [comment]
Why do you ask me? This module changes values of tunable parameters of an OS only, and doesn't include anything else. This module might become a trigger for an app or a kernel to do something, but it's up to them.

I haven't hear such restarting till now. I think you should change Kitsune Magisk to Official or change ROM.
