### ISSUE TITLE
I can't disable all audio effects on my device(Xiaomi 11T)

### ISSUE THREAD

**Issue by jyuuren** [yzyhk904/hifi-maximizer-mod#19]
First of all thank you for this magisk module, i like using it. My issue is, i can't disable all audio effects on my device even i ignore all audio effects in system.prop file. There is always channel mismatch in stereo. Frequency response for right and left channel is not the same. I know this because for example when i use JamesDSP to swap channels, frequency response also swaps for channels. I think this issue caused by manufacturers effort to somewhat balance stereo speakers of the phone but this audio effect applies all outputs(Bluetooth, external dac, etc.). Also, even if i deleted all the files in system/vendor/lib/soundfx and system/lib/soundfx using magisk replace tool, this audio effect still remains on(i also did the same for lib64/soundfx). I can't find any solution to this on the internet. This audio effects seems to embedded in firmware not the software. Can you help me with this issue please?

**Comment by yzyhk904** [comment]
I think it isn't any effect handled by the effects framework on Android. For example, DRC (Dynamic Range Control; in short a kind of compression) is forced for all audio outputs on almost only Snapdragon devices in audio hal's or external USB devices. MTK devices don't force DRC by default.

By any chance, you feel no DRC on MTK devices? You can check this by [USB SampleRate Changer](https://github.com/yzyhk904/USB_SampleRate_Changer) with/without "--drc" option.

**Comment by jyuuren** [comment]
I executed USB Sample Rate Changer script with and without "--drc" option and it seem to make no difference at channel mismatch.

**Comment by yzyhk904** [comment]
Did you set the mount mode of a name space in Magisk to be global? 

If so, I have no idea for such mismatch.

**Comment by jyuuren** [comment]
I did change namespace to global, issue still persists. I think issue caused by Mediatek Aurisys DSP libraries but when i nullify the "libaurisysdemo.so" file which is at /vendor/lib, audio function of the phone lost compeletly which prevents me from disabling mediatek related audio dsp libraries. Also my phone has special partition which is called "audio_dsp.img" at fastboot ROM images. I think this issue related with those things.

**Comment by yzyhk904** [comment]
Do you use HyperOS or MIUI on your device? I've been feeling somewhat strange sound (not mismatch) on HyperOS. I guess this effect from its volume manager.

If you feel the same as I, install GSI by using DSU. The effect would disappear on an AOSP GSI ROM.

**Comment by jyuuren** [comment]
I am currently using MIUI 13. I tried multiple GSI ROMs including AOSP GSI but these did not fixed it. GSI ROMs also had vendor folder so i guess that's why it didn't get fixed.
