### ISSUE TITLE
Switching SELinux Permissive without user consent and all cam apps (incl. Face Unlock) crashes

### ISSUE THREAD

**Issue by bcrtvkcs** [yzyhk904/hifi-maximizer-mod#21]
As seen in the title

OnePlus 9 Pro - crDroid 10.8

**Comment by yzyhk904** [comment]
See README! 

They are main features of this module for raising audio quality.

**Comment by bcrtvkcs** [comment]
All the camera apps crashes anyway.

**Comment by yzyhk904** [comment]
See README again carefully!

Disabling camera servers is a main feature for raising audio quality ultimately. This module has been designed for audiophile experts, but not for casual users.

**Comment by bcrtvkcs** [comment]
Good work thank you.
