### ISSUE TITLE
idea: make version of all your magisk mods merged and less intrusive

### ISSUE THREAD

**Issue by fxzzi** [yzyhk904/hifi-maximizer-mod#27]
As a replacement for the set and forget "Ainur Narsil" which hasnt been updated in a few years, I would love to move to your modules however they are very intrusive with blocking battery saving features, blocking camera access, changing selinux, as well as other things like changing the volume steps (100 is quite a lot, I use 50 usually).

Details about narsil is here: https://xdaforums.com/t/ainur-audio-sauron-mk-iii-paused-narsil-mk-i-upd-09-09-2021.3450516/post-68427401

As explained there:

> This Mod cleans android sfx from both stock and OEM effects as much as possible - delivering unbound sound the way hardware (internal codecs/dacs/amps) was meant to sound by manufacturer. It’s a system-wide modification - meaning it should affect general playback outputs: headphones/speaker/bt).

Would it be too troubling to create a version of your modules which is better than narsil, actively maintained and not too intrusive for regular phone usage?

Thanks :)

**Comment by yzyhk904** [comment]
I think the approach of Narsil is wrong. The crucial point is jitter affected easily by all batter savers and other servers.

This module is designed only for audiophile experts who believe the audio quality should be most important. There is my another module [Audio Misc. Settings](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings) for casual music lovers! I think you should go this module.

**Comment by fxzzi** [comment]
thank you!! I will check out audio misc settings. It also changes volume steps to 100, which is quite a lot for casual phone use. narsil offers a configuration file in /sdcard/ where you can modify things like the volume steps. Is this a possible addition to the module?

To confirm, only these modules are required for plug and play? I used a CX1993 usb c dac.
![Screenshot_20241208-225636](https://github.com/user-attachments/assets/1d6d6216-9acb-47b0-9cf2-6412a66c7858)

After installing these modules, my volume is lower, is this intended? I'm fine with it but just checking if it's correct behaviour. I have to play my music at 70% volume instead of 40%

**Comment by yzyhk904** [comment]
I strongly recommend you using [Audio Jitter Silencer](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer) in addition.

100 step (about 0.5 dB precision) volume is necessary for experienced audio users. 50 step (about 1 dB precision) volume is usually for audio beginners or adopted for cheap audio equipment. Do you know you can change volume quickly by GUI or long pushing? Till now there is nobody (who knows it) complaining about the steps.

Audio misc. disables equalizers and "Sound Dose" for health (?) that usually lowers the max volume level about 6dB. You can output sound without limiters and volume boosters.

**Comment by fxzzi** [comment]
Cool, I've installed that one too. Btw, is magisk mirror module still needed for latest 28.1 and canary? Changelog shows stuff about overlay.d: https://topjohnwu.github.io/Magisk/changes.html

I know you can hold to change the volume faster. It's still a little slow and if I'm being honest - more precise than I would really need. Plus my custom rom offers the volume steps option itself.

Cool. Thanks for the explanation on lower volume. This makes sense since you don't want to boost the volume at all if you don't have to.

**Comment by yzyhk904** [comment]
Although it's a bad news, "Compatible Magisk-mirroring" is still needed for Magisk v28.1.
