### ISSUE TITLE
Camera Disabled and AdGuard Delays on OnePlus 9 (CRDroid) android 13x

### ISSUE THREAD

**Issue by jaywrock** [yzyhk904/hifi-maximizer-mod#28]
Issue: Camera Disabled and Boot Sequence Delays on OnePlus 9 (CRDroid)

Hi,

First off, thank you for your incredible work on HiFi Maximizer and other audio modules! I’ve successfully used a few of your modules without issues, but I wanted to report significant problems specifically with HiFi Maximizer on my setup.

Device Details
Device: OnePlus 9 (T-Mobile)
Processor: Snapdragon
ROM: CRDroid 9.7 android 13
Root: Magisk 26.x
Other Mods: LSPosed, Lucky Patcher, AdGuard
Observed Issues
Camera Disabled: After installing this module, my camera (and flashlight) completely stopped working. I confirmed this was caused by the module after testing with proper uninstall/install sequences and various configurations.
AdGuard Boot Delay: This module caused significant delays during AdGuard initialization at boot.
AdGuard resets multiple times during boot, leaving a window where DNS requests from apps are unprotected. This undermines the DNS firewall’s primary purpose of blocking trackers during app initialization.
Common Observation Across Your Modules: While most of your modules cause minor AdGuard delays, this one had a disproportionately large impact.
Additional Context
I’ve used three of your other audio modules with zero hardware or camera issues.
My setup is very heavily modified, with ~7 Magisk modules, ~5 LSPosed modules, and numerous other customizations. It’s possible the issue stems from a conflict unique to my configuration rather than your module alone.
This issue was challenging to isolate due to the number of changes I made that day, but after extensive troubleshooting (and some misdirections), I determined this module was the root cause.
Suggestions for Others
If you rely on AdGuard’s DNS firewall during boot or use a heavily modded setup, this module may cause issues such as:

Camera or flashlight failure.
Compromised boot performance and unprotected DNS queries during startup.
Final Thoughts
Thank you again for creating such useful tools! I hope this feedback is helpful in improving compatibility for others with heavily customized setups. While I lack developer-level skills, I’d estimate with about 60% confidence that this module, even running alone on my device, would likely have caused the camera issue.

Here’s a [link to the ChatGPT troubleshooting session 
https://chatgpt.com/share/67667185-f278-8003-8f38-7646ab255b50 I used to diagnose the problem.

Thanks again, and I hope this helps others avoid the hours of troubleshooting I went through.

**Comment by yzyhk904** [comment]
Please read README! My answer is already there.  Disabling the camera server is a feature of this module because the camera server causes degradation of audio quality significantly.

My modules don't do anything for DNS and AdGuard. I think it's an issue of AdGuard.

**Comment by jaywrock** [comment]
Hi,

First and foremost, thank you for your exceptional work on these modules. It’s clear that a great deal of expertise and effort has gone into creating them, and your thorough documentation reflects that. That said, I’d like to share some feedback, including how I diagnosed an issue and ultimately came up with a solution, in the hopes that it helps improve the user experience for others.

I recently installed your HiFi Maximizer module, aiming to enhance audio performance. While the audio quality improvements were excellent, I encountered a significant issue: the module completely disables the camera, regardless of whether headphones are in use. For users like me, who rely on their cameras for tasks like using the flashlight, scanning QR codes, performing OCR for documents, or even making video calls with family, this is a critical functionality loss. Many people, myself included, might not initially connect an audio enhancement module with camera-related changes, so it’s essential that this impact is emphasized early in the module description—ideally at the very top.

I would like to clarify that I never was in the interpretation that it directly interfered with Adguard on the code level,  I just did notice that at boot adguard usually started almost immediately as it was high up on the list Of the boot sequence but with this module and possibly some of your other ones if I recall, during that first 30 seconds Of Adguard Try to initialize and put up the firewall even though I didn't do any packet testing I do know when Adgurd would start and then resets it's self, which definitely delayed it's final protection abut 10-15 seconds. And since I had to reboot my phone About twenty times as I use the process of deduction of uninstalling each one of my magistinal's post modules it was consistent until I uninstalled the Hifi maximizer. And to be quite honest since I use so many of your modules before you never had a high problem it was almost the last module that I thought could be the problem because I never made the connection Of an audio module affecting the camera but I very much understand and trust your professional opinion that it probably does affect audio quality, and maybe you're probably just in a different league of audio file where you're willing to make that trade off of audio quality for a camera and for many settings this is probably very appropriate and desired. Again this is a one out circumstance where if you just installed one or 2 modules you could obviously conclude that it was probably the last module you installed that's the culprit but that day I literally installed in uninstalled and tried different software for about 12 hours so I probably did a total of 60 installs in 55 uninstalls that day and yours was the first and oddly enough one that I thought was most trustworthy because I never had a bad experience using your modules in The trust was very high because your descripcion obviously showed you know what you were talking about.

The way I discovered this issue is worth noting. I was about ready to write back At the same time I saw a little green dot on my Github that I got a message. I I'm guessing that in this community the premise is kind of a installer beware type of situation and I felt like an idiot because it was there in black and white buried in your description that it did affect the camera . However I didn't find this by reading the description as it was somewhat out of my league in using Jargon I didn't understand I went back in looked at code for the module to better understand how it works and cross-referenced that with your documentation. While the description does mention how the module tweaks the camera functionality, it didn’t explicitly state that the camera would be rendered entirely non-functional. This realization only came after some troubleshooting and carefully examining the module’s effects in detail. (This is a learning lesson for me to get better at reading and understanding code and be more villagent about looking at it before I install something not, because I think there's anything malicious per se but just so I can understand exactly what it is that I'm doing and to prevent other conflicts)

For context, I’ve been modding Android devices for over 12 years, and my setup is heavily customized with Magisk, LSPosed, and other modifications. This kind of deep dive into the code may be second nature to some developers, but many others may not be aware of the potential trade-offs when installing the module. Adding a prominent warning in the module description could save users from similar confusion or unintended consequences, especially since the camera is such an integral part of daily phone use.

On a more personal note, I’m an audio enthusiast with a background as a club DJ. I’ve always invested in high-quality audio gear, including my recently lost Technics AZ60 earbuds, which cost $180. Unfortunately, I misplaced them at a Chick-fil-A (lesson learned!). Now, I’m using TOZO NC9 earbuds and trying to optimize their performance while I save up for a replacement. If you have any recommendations for modules that might work better with my current hardware and earbuds, I’d love to hear them.

Finally, I want to reiterate my appreciation for your work. This isn’t meant as a criticism but as constructive feedback to make your excellent modules even more user-friendly. Thank you again for your dedication to the community and for sharing your expertise with us all. (Sorry if this post is too long but I'm somewhat a lonely loser and have not many people to talk to...lol

MyDevice Details
Device: OnePlus 9 (T-Mobile)
Processor: Snapdragon
ROM: CRDroid 9.7 android 13
Root: Magisk 26.x
Other Mods: LSPosed, Lucky Patcher, AdGuard

 **TOZO NC9**  2002 model

| Feature                      | Details                                |
|------------------------------|----------------------------------------|
| **Model**                    | NC9                                    |
| **Type**                     | In-ear True Wireless                  |
| **Color Options**            | Matte Black, Khaki, White, Red, Royal Blue, Dark Brown |
| **Driver Size**              | 9mm dynamic driver                     |
| **Frequency Response Range** | 14Hz - 20kHz                          |
| **Audio Codecs Supported**   | AAC, SBC                              |
| **Bluetooth Version**        | 5.3                                    |
| **Effective Bluetooth Range**| Up to 10m                             |
| **Battery Capacity**         | Earphones: 70mAh; Charging Case: 500mAh |
| **Music Play Time**          | Up to 18h (single charge), 72h (with charging case) |
| **Charging Time**            | 2h for both earphones and case        |
| **Charging Port**            | USB Type-C; supports wireless charging |
| **Water Resistance Rating**  | IPX6                                   |
| **Noise Control Modes**      | Noise Cancellation, Leisure Mode, Custom Pattern, Transparency Mode |
| **Call Noise Cancellation**  | Dual-microphone with ENC               |

**Comment by yzyhk904** [comment]
This module disables SELinux and even thermal throttling for ultimate audio quality. In short, it makes your device to be specific to audio playback only or to be an ultimate DAP. I've not intended it for other uses till now. So, this module hasn't been released from the Magisk-Alt-Repo.

If you use your device for multi purpose, please use [Audio Misc. Settings](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings) that has been designed for casual music lovers.
