### ISSUE TITLE
All google apps crushing

### ISSUE THREAD

**Issue by heanyrj** [yzyhk904/hifi-maximizer-mod#29]
GCAM  and the Face ID does not work on the Pixel 6 android 15 official firmware. On the Redmi Note 7 Crdroid 10.11 Crushing Google application when I launch, face id on start phone, and GCAM. In Google services it is not possible to enter the account.

**Comment by heanyrj** [comment]
youtube stuck on logo

**Comment by yzyhk904** [comment]
See README!
