### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by fillwithjoy1** [yzyhk904/hifi-maximizer-mod#5]
Hey I'm wondering if this module drains battery, as it does seem to force my CPU governor to performance and disables doze completely

**Comment by yzyhk904** [comment]
Don't worry if you are an audiophile. All for ultimate audio quality! 

If you are thinking about balancing between audio quality and battery usage, I recommend to use my another module [Audio misc. settings](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings) instead.

Actually, battery usage is depend on your device, OS, how you use apps. On a good device and OS, battery usage of a music streaming service only is about 2% per hour for bluetooth earphones or 3.5mm jack head phones with Wifi (5GHz) only (Air plane mode).

Performance governor and disabling doze don't affect significantly to battery usage on a good device, OS and app usage. Try this module if you are an audiophile (perhaps, and think that your device is good enough)!

Edit: Don't forget to install [Audio jitter silencer](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer). Doze cannot be disabled completely by Hifi maximizer only. Need this module with!
