### ISSUE TITLE
Conflict to camera pixel 7 pro

### ISSUE THREAD

**Issue by PrincessOfHell** [yzyhk904/hifi-maximizer-mod#7]
When I activate the module, the pixel 7 pro camera stops working.  Other camera apps also do not have access to the camera.  I think it is a camera hardware problem that conflicts with the changes that this module makes to the system.  I deactivate the module, restart the phone and the camera app works again, the other camera apps too.
It is a very strange error.

**Comment by PrincessOfHell** [comment]
I attach a screenshot of the camera app error

![Screenshot_20231020-133124](https://github.com/yzyhk904/hifi-maximizer-mod/assets/1158444/ecc51bf2-483b-45e1-8af0-645d689655ba)

**Comment by yzyhk904** [comment]
It's also a main feature of this mod. Please see README.md.

> Note1: Please remember that this module will stop the thermal control (including CPU core controls, CPU hotplugs and thermal services), the "logd server" and the "camera server" (interfering jitter on audio outputs), disable SELinux enforcing mode and doze (battery saver while idling) on your device. If you like to enable these features, modify variables in "service.sh", respectively. Especially, note that the "Youtube" app became recetly to need the camera server for launching for some unexplained reason.

Edit "service.sh" (line: 22) in the zip file of this mod like,

> EnableCameraService="yes"

And update the module with this modified one.

**Comment by PrincessOfHell** [comment]
thanks, it works.
