### ISSUE TITLE
Compatible Mod

### ISSUE THREAD

**Issue by 4adbfa76** [yzyhk904/hifi-maximizer-mod#9]
Is this module compatible with Ainur Narsil module?

**Comment by yzyhk904** [comment]
I don't know the module, but guess it isn't compatible.
Please uninstall it. I think my module itself is enough for audiophiles.

**Comment by 4adbfa76** [comment]
Module page on XDA: https://xdaforums.com/t/ainur-audio-sauron-mk-iii-paused-narsil-mk-i-upd-09-09-2021.3450516/

While checking Magisk log i see both module making the same changes with some differences. I believe both can work together with Audio Modification Library(AML) by @Zackptg5.

**Comment by yzyhk904** [comment]
I guess the modules modify an audio policy file and configurations of internal speakers & 3.5mm jack. If you use a USB DAC or BT earphones, they would have no effects over my module.
